"""add grade_scale to topic test

Revision ID: 0fa13e384642
Revises: a1b2c3d4e5f6
Create Date: 2026-06-18 21:06:37.652694
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '0fa13e384642'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def drop_constraint_if_exists(constraint_name, table_name, type_="unique"):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if type_ == "unique":
        constraints = inspector.get_unique_constraints(table_name)
        if any(c["name"] == constraint_name for c in constraints):
            drop_constraint_if_exists(constraint_name, table_name, type_=type_)
    elif type_ == "foreignkey":
        constraints = inspector.get_foreign_keys(table_name)
        if any(c["name"] == constraint_name for c in constraints):
            drop_constraint_if_exists(constraint_name, table_name, type_=type_)
    elif type_ == "primary":
        pk = inspector.get_pk_constraint(table_name)
        if pk and pk.get("name") == constraint_name:
            drop_constraint_if_exists(constraint_name, table_name, type_=type_)

def create_unique_constraint_if_not_exists(constraint_name, table_name, columns):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = inspector.get_unique_constraints(table_name)
    if not any(c["name"] == constraint_name for c in constraints):
        create_unique_constraint_if_not_exists(constraint_name, table_name, columns)

def create_foreign_key_if_not_exists(constraint_name, source_table, refer_table, local_cols, remote_cols, **kwargs):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = inspector.get_foreign_keys(source_table)
    if not any(c["name"] == constraint_name for c in constraints):
        create_foreign_key_if_not_exists(constraint_name, source_table, refer_table, local_cols, remote_cols, **kwargs)


def drop_index_if_exists(index_name, table_name):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = inspector.get_indexes(table_name)
    if any(idx["name"] == index_name for idx in indexes):
        drop_index_if_exists(index_name, table_name=table_name)

def create_index_if_not_exists(index_name, table_name, columns, **kwargs):
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    indexes = inspector.get_indexes(table_name)
    if not any(idx["name"] == index_name for idx in indexes):
        create_index_if_not_exists(index_name, table_name, columns, **kwargs)

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    if 'admin_audit_summary' in inspector.get_table_names():
        op.drop_table('admin_audit_summary')
    drop_constraint_if_exists(op.f('admins_email_key'), 'admins', type_='unique')
    drop_constraint_if_exists(op.f('admins_login_key'), 'admins', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_admins_email'), 'admins', ['email'])
    create_unique_constraint_if_not_exists(op.f('uq_admins_login'), 'admins', ['login'])
    op.alter_column('answer_comments', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('answer_comments', 'question_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('answer_comments', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('answer_extra', 'answer_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('answer_extra', 'match_pairs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('answer_options', 'option_number',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Номер варианта 1..4',
               existing_nullable=False)
    op.alter_column('answer_options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               comment=None,
               existing_comment='TRUE только у правильного варианта',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    drop_index_if_exists(op.f('idx_options_question_id'), table_name='answer_options')
    drop_constraint_if_exists(op.f('uq_option_number_per_question'), 'answer_options', type_='unique')
    drop_constraint_if_exists(op.f('fk_option_question'), 'answer_options', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_answer_options_question_id_questions'), 'answer_options', 'questions', ['question_id'], ['question_id'], ondelete='CASCADE')
    op.drop_table_comment(
        'answer_options',
        existing_comment='Варианты ответов (4 на вопрос)',
        schema=None
    )
    op.alter_column('attempts_policy', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('attempts_policy', 'discipline_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('attempts_policy_teacher_id_discipline_id_key'), 'attempts_policy', type_='unique')
    create_unique_constraint_if_not_exists('uq_policy_teacher_disc', 'attempts_policy', ['teacher_id', 'discipline_id'])
    op.alter_column('audit_log', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_log', 'before_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_log', 'after_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('discipline_images', 'sha256_hex',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('discipline_images_discipline_id_key'), 'discipline_images', type_='unique')
    drop_constraint_if_exists(op.f('discipline_images_storage_key_key'), 'discipline_images', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_discipline_images_discipline_id'), 'discipline_images', ['discipline_id'])
    create_unique_constraint_if_not_exists(op.f('uq_discipline_images_storage_key'), 'discipline_images', ['storage_key'])
    op.alter_column('discipline_topic_images', 'sha256_hex',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('discipline_topic_images_storage_key_key'), 'discipline_topic_images', type_='unique')
    drop_constraint_if_exists(op.f('discipline_topic_images_topic_id_key'), 'discipline_topic_images', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_discipline_topic_images_storage_key'), 'discipline_topic_images', ['storage_key'])
    create_unique_constraint_if_not_exists(op.f('uq_discipline_topic_images_topic_id'), 'discipline_topic_images', ['topic_id'])
    drop_index_if_exists(op.f('idx_discipline_topics_archived'), table_name='discipline_topics')
    drop_constraint_if_exists(op.f('disciplines_name_key'), 'disciplines', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_disciplines_name'), 'disciplines', ['name'])
    op.drop_table_comment(
        'disciplines',
        existing_comment='Учебные дисциплины',
        schema=None
    )
    op.alter_column('groups', 'group_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID группы',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment=None,
               existing_comment='Шифр группы (например, ИВТ-21)',
               existing_nullable=False)
    op.alter_column('groups', 'admission_year',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Год поступления',
               existing_nullable=False)
    drop_constraint_if_exists(op.f('groups_name_key'), 'groups', type_='unique')
    op.drop_table_comment(
        'groups',
        existing_comment='Учебные группы',
        schema=None
    )
    op.alter_column('notifications', 'payload',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('notifications', 'severity',
               existing_type=sa.SMALLINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    drop_constraint_if_exists(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_password_reset_tokens_token_hash'), 'password_reset_tokens', ['token_hash'])
    op.alter_column('proctor_events', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('proctor_events', 'metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('question_cloze_blanks', 'kind',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.String(length=16),
               existing_nullable=False)
    op.alter_column('question_cloze_blanks', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('question_cloze_blanks', 'acceptable_answers',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('question_images', 'sha256_hex',
               existing_type=sa.CHAR(length=64),
               type_=sa.String(length=64),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('question_images_question_id_key'), 'question_images', type_='unique')
    drop_constraint_if_exists(op.f('question_images_storage_key_key'), 'question_images', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_question_images_question_id'), 'question_images', ['question_id'])
    create_unique_constraint_if_not_exists(op.f('uq_question_images_storage_key'), 'question_images', ['storage_key'])
    op.alter_column('question_tag_map', 'question_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Сложность: 1 — легко, 5 — сложно',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('questions', 'match_pairs',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    drop_index_if_exists(op.f('idx_questions_discipline_id'), table_name='questions')
    drop_constraint_if_exists(op.f('fk_question_discipline'), 'questions', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_questions_discipline_id_disciplines'), 'questions', 'disciplines', ['discipline_id'], ['discipline_id'], ondelete='CASCADE')
    op.drop_table_comment(
        'questions',
        existing_comment='Вопросы тестирования',
        schema=None
    )
    drop_index_if_exists(op.f('idx_sa_selected_option_id'), table_name='student_answers')
    drop_index_if_exists(op.f('idx_sa_session_id'), table_name='student_answers')
    drop_constraint_if_exists(op.f('fk_sa_option_v2'), 'student_answers', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_sa_question'), 'student_answers', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_sa_session'), 'student_answers', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_student_answers_question_id_questions'), 'student_answers', 'questions', ['question_id'], ['question_id'])
    create_foreign_key_if_not_exists(op.f('fk_student_answers_session_id_test_sessions'), 'student_answers', 'test_sessions', ['session_id'], ['session_id'], ondelete='CASCADE')
    create_foreign_key_if_not_exists(op.f('fk_student_answers_selected_option_id_answer_options'), 'student_answers', 'answer_options', ['selected_option_id'], ['option_id'])
    op.drop_table_comment(
        'student_answers',
        existing_comment='Ответы студента в рамках сессии',
        schema=None
    )
    op.alter_column('students', 'student_id',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='ID студента',
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment=None,
               existing_comment='Уникальный email (логин)',
               existing_nullable=False)
    op.alter_column('students', 'login',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    drop_index_if_exists(op.f('idx_students_group_id'), table_name='students')
    drop_index_if_exists(op.f('idx_students_last_name'), table_name='students')
    drop_constraint_if_exists(op.f('students_email_key'), 'students', type_='unique')
    drop_constraint_if_exists(op.f('students_login_unique'), 'students', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_students_email'), 'students', ['email'])
    create_unique_constraint_if_not_exists(op.f('uq_students_login'), 'students', ['login'])
    drop_constraint_if_exists(op.f('fk_student_group'), 'students', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_students_group_id_groups'), 'students', 'groups', ['group_id'], ['group_id'])
    op.drop_table_comment(
        'students',
        existing_comment='Студенты',
        schema=None
    )
    op.alter_column('teacher_audit_log', 'before',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('teacher_audit_log', 'after',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    create_foreign_key_if_not_exists(op.f('fk_teacher_audit_log_teacher_id_teachers'), 'teacher_audit_log', 'teachers', ['teacher_id'], ['teacher_id'])
    drop_index_if_exists(op.f('idx_td_discipline_id'), table_name='teacher_disciplines')
    drop_constraint_if_exists(op.f('fk_td_teacher'), 'teacher_disciplines', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_td_discipline'), 'teacher_disciplines', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_teacher_disciplines_teacher_id_teachers'), 'teacher_disciplines', 'teachers', ['teacher_id'], ['teacher_id'], ondelete='CASCADE')
    create_foreign_key_if_not_exists(op.f('fk_teacher_disciplines_discipline_id_disciplines'), 'teacher_disciplines', 'disciplines', ['discipline_id'], ['discipline_id'], ondelete='CASCADE')
    op.drop_table_comment(
        'teacher_disciplines',
        existing_comment='Какие дисциплины ведёт преподаватель',
        schema=None
    )
    op.alter_column('teacher_groups', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('teacher_groups', 'group_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.add_column('teacher_topic_tests', sa.Column('grade_scale', sa.String(length=16), server_default='5_point', nullable=False))
    create_index_if_not_exists('idx_teacher_topic_tests_topic', 'teacher_topic_tests', ['topic_id'], unique=False)
    op.alter_column('teachers', 'login',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    drop_index_if_exists(op.f('idx_teachers_last_name'), table_name='teachers')
    drop_constraint_if_exists(op.f('teachers_email_key'), 'teachers', type_='unique')
    drop_constraint_if_exists(op.f('teachers_login_unique'), 'teachers', type_='unique')
    create_unique_constraint_if_not_exists(op.f('uq_teachers_email'), 'teachers', ['email'])
    create_unique_constraint_if_not_exists(op.f('uq_teachers_login'), 'teachers', ['login'])
    op.drop_table_comment(
        'teachers',
        existing_comment='Преподаватели',
        schema=None
    )
    op.alter_column('test_sessions', 'score',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='Набранные баллы (вычисляется триггером/приложением)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    drop_index_if_exists(op.f('idx_sessions_discipline_id'), table_name='test_sessions')
    drop_index_if_exists(op.f('idx_sessions_student_id'), table_name='test_sessions')
    drop_index_if_exists(op.f('idx_sessions_teacher_id'), table_name='test_sessions')
    drop_constraint_if_exists(op.f('fk_session_discipline'), 'test_sessions', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_session_teacher'), 'test_sessions', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_session_student'), 'test_sessions', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_test_sessions_discipline_id_disciplines'), 'test_sessions', 'disciplines', ['discipline_id'], ['discipline_id'])
    create_foreign_key_if_not_exists(op.f('fk_test_sessions_teacher_id_teachers'), 'test_sessions', 'teachers', ['teacher_id'], ['teacher_id'])
    create_foreign_key_if_not_exists(op.f('fk_test_sessions_student_id_students'), 'test_sessions', 'students', ['student_id'], ['student_id'])
    op.drop_table_comment(
        'test_sessions',
        existing_comment='Попытки прохождения теста',
        schema=None
    )
    op.alter_column('test_sessions_grade_override', 'session_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('test_sessions_grade_override', 'teacher_id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('user_credentials_role_user_id_key'), 'user_credentials', type_='unique')
    create_unique_constraint_if_not_exists('uq_credential_role_user', 'user_credentials', ['role', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    drop_constraint_if_exists('uq_credential_role_user', 'user_credentials', type_='unique')
    create_unique_constraint_if_not_exists(op.f('user_credentials_role_user_id_key'), 'user_credentials', ['role', 'user_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('test_sessions_grade_override', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('test_sessions_grade_override', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table_comment(
        'test_sessions',
        'Попытки прохождения теста',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('fk_test_sessions_student_id_students'), 'test_sessions', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_test_sessions_teacher_id_teachers'), 'test_sessions', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_test_sessions_discipline_id_disciplines'), 'test_sessions', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_session_student'), 'test_sessions', 'students', ['student_id'], ['student_id'], onupdate='CASCADE', ondelete='RESTRICT')
    create_foreign_key_if_not_exists(op.f('fk_session_teacher'), 'test_sessions', 'teachers', ['teacher_id'], ['teacher_id'], onupdate='CASCADE', ondelete='RESTRICT')
    create_foreign_key_if_not_exists(op.f('fk_session_discipline'), 'test_sessions', 'disciplines', ['discipline_id'], ['discipline_id'], onupdate='CASCADE', ondelete='RESTRICT')
    create_index_if_not_exists(op.f('idx_sessions_teacher_id'), 'test_sessions', ['teacher_id'], unique=False)
    create_index_if_not_exists(op.f('idx_sessions_student_id'), 'test_sessions', ['student_id'], unique=False)
    create_index_if_not_exists(op.f('idx_sessions_discipline_id'), 'test_sessions', ['discipline_id'], unique=False)
    op.alter_column('test_sessions', 'score',
               existing_type=sa.INTEGER(),
               comment='Набранные баллы (вычисляется триггером/приложением)',
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.create_table_comment(
        'teachers',
        'Преподаватели',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('uq_teachers_login'), 'teachers', type_='unique')
    drop_constraint_if_exists(op.f('uq_teachers_email'), 'teachers', type_='unique')
    create_unique_constraint_if_not_exists(op.f('teachers_login_unique'), 'teachers', ['login'], postgresql_nulls_not_distinct=False)
    create_unique_constraint_if_not_exists(op.f('teachers_email_key'), 'teachers', ['email'], postgresql_nulls_not_distinct=False)
    create_index_if_not_exists(op.f('idx_teachers_last_name'), 'teachers', ['last_name'], unique=False)
    op.alter_column('teachers', 'login',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    drop_index_if_exists('idx_teacher_topic_tests_topic', table_name='teacher_topic_tests')
    op.drop_column('teacher_topic_tests', 'grade_scale')
    op.alter_column('teacher_groups', 'group_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('teacher_groups', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table_comment(
        'teacher_disciplines',
        'Какие дисциплины ведёт преподаватель',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('fk_teacher_disciplines_discipline_id_disciplines'), 'teacher_disciplines', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_teacher_disciplines_teacher_id_teachers'), 'teacher_disciplines', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_td_discipline'), 'teacher_disciplines', 'disciplines', ['discipline_id'], ['discipline_id'], onupdate='CASCADE', ondelete='CASCADE')
    create_foreign_key_if_not_exists(op.f('fk_td_teacher'), 'teacher_disciplines', 'teachers', ['teacher_id'], ['teacher_id'], onupdate='CASCADE', ondelete='CASCADE')
    create_index_if_not_exists(op.f('idx_td_discipline_id'), 'teacher_disciplines', ['discipline_id'], unique=False)
    drop_constraint_if_exists(op.f('fk_teacher_audit_log_teacher_id_teachers'), 'teacher_audit_log', type_='foreignkey')
    op.alter_column('teacher_audit_log', 'after',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('teacher_audit_log', 'before',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table_comment(
        'students',
        'Студенты',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('fk_students_group_id_groups'), 'students', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_student_group'), 'students', 'groups', ['group_id'], ['group_id'], onupdate='CASCADE', ondelete='RESTRICT')
    drop_constraint_if_exists(op.f('uq_students_login'), 'students', type_='unique')
    drop_constraint_if_exists(op.f('uq_students_email'), 'students', type_='unique')
    create_unique_constraint_if_not_exists(op.f('students_login_unique'), 'students', ['login'], postgresql_nulls_not_distinct=False)
    create_unique_constraint_if_not_exists(op.f('students_email_key'), 'students', ['email'], postgresql_nulls_not_distinct=False)
    create_index_if_not_exists(op.f('idx_students_last_name'), 'students', ['last_name'], unique=False)
    create_index_if_not_exists(op.f('idx_students_group_id'), 'students', ['group_id'], unique=False)
    op.alter_column('students', 'login',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('students', 'email',
               existing_type=sa.VARCHAR(length=255),
               comment='Уникальный email (логин)',
               existing_nullable=False)
    op.alter_column('students', 'student_id',
               existing_type=sa.INTEGER(),
               comment='ID студента',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'student_answers',
        'Ответы студента в рамках сессии',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('fk_student_answers_selected_option_id_answer_options'), 'student_answers', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_student_answers_session_id_test_sessions'), 'student_answers', type_='foreignkey')
    drop_constraint_if_exists(op.f('fk_student_answers_question_id_questions'), 'student_answers', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_sa_session'), 'student_answers', 'test_sessions', ['session_id'], ['session_id'], onupdate='CASCADE', ondelete='CASCADE')
    create_foreign_key_if_not_exists(op.f('fk_sa_question'), 'student_answers', 'questions', ['question_id'], ['question_id'], onupdate='CASCADE', ondelete='RESTRICT')
    create_foreign_key_if_not_exists(op.f('fk_sa_option_v2'), 'student_answers', 'answer_options', ['selected_option_id'], ['option_id'], onupdate='CASCADE', ondelete='RESTRICT')
    create_index_if_not_exists(op.f('idx_sa_session_id'), 'student_answers', ['session_id'], unique=False)
    create_index_if_not_exists(op.f('idx_sa_selected_option_id'), 'student_answers', ['selected_option_id'], unique=False)
    op.create_table_comment(
        'questions',
        'Вопросы тестирования',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('fk_questions_discipline_id_disciplines'), 'questions', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_question_discipline'), 'questions', 'disciplines', ['discipline_id'], ['discipline_id'], onupdate='CASCADE', ondelete='CASCADE')
    create_index_if_not_exists(op.f('idx_questions_discipline_id'), 'questions', ['discipline_id'], unique=False)
    op.alter_column('questions', 'match_pairs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('questions', 'difficulty',
               existing_type=sa.INTEGER(),
               comment='Сложность: 1 — легко, 5 — сложно',
               existing_nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('question_tag_map', 'question_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('uq_question_images_storage_key'), 'question_images', type_='unique')
    drop_constraint_if_exists(op.f('uq_question_images_question_id'), 'question_images', type_='unique')
    create_unique_constraint_if_not_exists(op.f('question_images_storage_key_key'), 'question_images', ['storage_key'], postgresql_nulls_not_distinct=False)
    create_unique_constraint_if_not_exists(op.f('question_images_question_id_key'), 'question_images', ['question_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('question_images', 'sha256_hex',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('question_cloze_blanks', 'acceptable_answers',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('question_cloze_blanks', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('question_cloze_blanks', 'kind',
               existing_type=sa.String(length=16),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
    op.alter_column('proctor_events', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('proctor_events', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('uq_password_reset_tokens_token_hash'), 'password_reset_tokens', type_='unique')
    create_unique_constraint_if_not_exists(op.f('password_reset_tokens_token_hash_key'), 'password_reset_tokens', ['token_hash'], postgresql_nulls_not_distinct=False)
    op.alter_column('notifications', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('notifications', 'severity',
               existing_type=sa.Integer(),
               type_=sa.SMALLINT(),
               existing_nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('notifications', 'payload',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_table_comment(
        'groups',
        'Учебные группы',
        existing_comment=None,
        schema=None
    )
    create_unique_constraint_if_not_exists(op.f('groups_name_key'), 'groups', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('groups', 'admission_year',
               existing_type=sa.INTEGER(),
               comment='Год поступления',
               existing_nullable=False)
    op.alter_column('groups', 'name',
               existing_type=sa.VARCHAR(length=50),
               comment='Шифр группы (например, ИВТ-21)',
               existing_nullable=False)
    op.alter_column('groups', 'group_id',
               existing_type=sa.INTEGER(),
               comment='ID группы',
               existing_nullable=False,
               autoincrement=True)
    op.create_table_comment(
        'disciplines',
        'Учебные дисциплины',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('uq_disciplines_name'), 'disciplines', type_='unique')
    create_unique_constraint_if_not_exists(op.f('disciplines_name_key'), 'disciplines', ['name'], postgresql_nulls_not_distinct=False)
    create_index_if_not_exists(op.f('idx_discipline_topics_archived'), 'discipline_topics', ['archived_at'], unique=False)
    drop_constraint_if_exists(op.f('uq_discipline_topic_images_topic_id'), 'discipline_topic_images', type_='unique')
    drop_constraint_if_exists(op.f('uq_discipline_topic_images_storage_key'), 'discipline_topic_images', type_='unique')
    create_unique_constraint_if_not_exists(op.f('discipline_topic_images_topic_id_key'), 'discipline_topic_images', ['topic_id'], postgresql_nulls_not_distinct=False)
    create_unique_constraint_if_not_exists(op.f('discipline_topic_images_storage_key_key'), 'discipline_topic_images', ['storage_key'], postgresql_nulls_not_distinct=False)
    op.alter_column('discipline_topic_images', 'sha256_hex',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('uq_discipline_images_storage_key'), 'discipline_images', type_='unique')
    drop_constraint_if_exists(op.f('uq_discipline_images_discipline_id'), 'discipline_images', type_='unique')
    create_unique_constraint_if_not_exists(op.f('discipline_images_storage_key_key'), 'discipline_images', ['storage_key'], postgresql_nulls_not_distinct=False)
    create_unique_constraint_if_not_exists(op.f('discipline_images_discipline_id_key'), 'discipline_images', ['discipline_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('discipline_images', 'sha256_hex',
               existing_type=sa.String(length=64),
               type_=sa.CHAR(length=64),
               existing_nullable=False)
    op.alter_column('audit_log', 'after_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_log', 'before_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_log', 'metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    drop_constraint_if_exists('uq_policy_teacher_disc', 'attempts_policy', type_='unique')
    create_unique_constraint_if_not_exists(op.f('attempts_policy_teacher_id_discipline_id_key'), 'attempts_policy', ['teacher_id', 'discipline_id'], postgresql_nulls_not_distinct=False)
    op.alter_column('attempts_policy', 'discipline_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('attempts_policy', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.create_table_comment(
        'answer_options',
        'Варианты ответов (4 на вопрос)',
        existing_comment=None,
        schema=None
    )
    drop_constraint_if_exists(op.f('fk_answer_options_question_id_questions'), 'answer_options', type_='foreignkey')
    create_foreign_key_if_not_exists(op.f('fk_option_question'), 'answer_options', 'questions', ['question_id'], ['question_id'], onupdate='CASCADE', ondelete='CASCADE')
    create_unique_constraint_if_not_exists(op.f('uq_option_number_per_question'), 'answer_options', ['question_id', 'option_number'], postgresql_nulls_not_distinct=False)
    create_index_if_not_exists(op.f('idx_options_question_id'), 'answer_options', ['question_id'], unique=False)
    op.alter_column('answer_options', 'is_correct',
               existing_type=sa.BOOLEAN(),
               comment='TRUE только у правильного варианта',
               existing_nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('answer_options', 'option_number',
               existing_type=sa.INTEGER(),
               comment='Номер варианта 1..4',
               existing_nullable=False)
    op.alter_column('answer_extra', 'match_pairs',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('answer_extra', 'answer_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('answer_comments', 'teacher_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('answer_comments', 'question_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('answer_comments', 'session_id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    drop_constraint_if_exists(op.f('uq_admins_login'), 'admins', type_='unique')
    drop_constraint_if_exists(op.f('uq_admins_email'), 'admins', type_='unique')
    create_unique_constraint_if_not_exists(op.f('admins_login_key'), 'admins', ['login'], postgresql_nulls_not_distinct=False)
    create_unique_constraint_if_not_exists(op.f('admins_email_key'), 'admins', ['email'], postgresql_nulls_not_distinct=False)
    op.create_table('admin_audit_summary',
    sa.Column('summary_id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('period_start', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('period_end', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('counts', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('generated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('summary_id', name=op.f('admin_audit_summary_pkey'))
    )
    # ### end Alembic commands ###
