"""add_teacher_topic_test_group_rules

Revision ID: 15fa183094d0
Revises: d7e8f9a0b1c2
Create Date: 2026-06-24 09:37:59.436110
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '15fa183094d0'
down_revision: Union[str, None] = 'd7e8f9a0b1c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_topic_test_group_rules',
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('fk_teacher_topic_test_group_rules_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['discipline_topics.topic_id'], name=op.f('fk_teacher_topic_test_group_rules_topic_id_discipline_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', 'group_id', name=op.f('pk_teacher_topic_test_group_rules'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_topic_test_group_rules')
    # ### end Alembic commands ###
