"""baseline: full schema

Revision ID: 8b64321488d4
Revises: 
Create Date: 2026-06-18 09:02:26.437627
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '8b64321488d4'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('department', sa.String(length=150), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('admin_id', name=op.f('pk_admins')),
    sa.UniqueConstraint('email', name=op.f('uq_admins_email')),
    sa.UniqueConstraint('login', name=op.f('uq_admins_login'))
    )
    op.create_index('idx_admins_archived', 'admins', ['archived_at'], unique=False)
    op.create_table('audit_log',
    sa.Column('log_id', sa.BigInteger(), nullable=False),
    sa.Column('actor_role', sa.String(length=16), nullable=True),
    sa.Column('actor_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('ip_addr', postgresql.INET(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('before_json', sa.JSON(), nullable=True),
    sa.Column('after_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('log_id', name=op.f('pk_audit_log'))
    )
    op.create_index('idx_audit_action', 'audit_log', ['action'], unique=False)
    op.create_index('idx_audit_actor', 'audit_log', ['actor_role', 'actor_id'], unique=False)
    op.create_index('idx_audit_created_at', 'audit_log', ['created_at'], unique=False)
    op.create_index('idx_audit_role_time', 'audit_log', ['actor_role', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_audit_target', 'audit_log', ['target_type', 'target_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('groups',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('admission_year', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('group_id', name=op.f('pk_groups'))
    )
    op.create_index('idx_groups_archived', 'groups', ['archived_at'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.BigInteger(), nullable=False),
    sa.Column('user_role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('recipient_role', sa.String(length=16), nullable=True),
    sa.Column('channel', sa.String(length=32), server_default='user', nullable=False),
    sa.Column('severity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('hidden_admin_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('notification_id', name=op.f('pk_notifications'))
    )
    op.create_index('idx_notifications_event_type', 'notifications', ['event_type', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_notifications_role_channel', 'notifications', ['recipient_role', 'channel', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_notifications_user', 'notifications', ['user_role', 'user_id', 'created_at'], unique=False)
    op.create_table('password_reset_tokens',
    sa.Column('token_id', sa.BigInteger(), nullable=False),
    sa.Column('user_role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('token_id', name=op.f('pk_password_reset_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_password_reset_tokens_token_hash'))
    )
    op.create_table('question_tags',
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('tag_id', name=op.f('pk_question_tags'))
    )
    op.create_index('idx_question_tags_archived', 'question_tags', ['archived_at'], unique=False)
    op.create_index('uq_question_tags_name_active', 'question_tags', ['name'], unique=True, postgresql_where=sa.text('archived_at IS NULL'))
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('department', sa.String(length=150), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id', name=op.f('pk_teachers')),
    sa.UniqueConstraint('email', name=op.f('uq_teachers_email')),
    sa.UniqueConstraint('login', name=op.f('uq_teachers_login'))
    )
    op.create_index('idx_teachers_archived', 'teachers', ['archived_at'], unique=False)
    op.create_table('user_credentials',
    sa.Column('credential_id', sa.BigInteger(), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('requires_totp', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('totp_secret', sa.String(length=64), nullable=True),
    sa.Column('totp_enrolled_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("role IN ('student','teacher','admin')", name=op.f('ck_user_credentials_chk_credential_role')),
    sa.PrimaryKeyConstraint('credential_id', name=op.f('pk_user_credentials')),
    sa.UniqueConstraint('role', 'user_id', name='uq_credential_role_user')
    )
    op.create_table('disciplines',
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('credits', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Integer(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.teacher_id'], name=op.f('fk_disciplines_created_by_teachers')),
    sa.PrimaryKeyConstraint('discipline_id', name=op.f('pk_disciplines')),
    sa.UniqueConstraint('name', name=op.f('uq_disciplines_name'))
    )
    op.create_index('idx_disciplines_archived', 'disciplines', ['archived_at'], unique=False)
    op.create_table('students',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('middle_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('login', sa.String(length=64), nullable=False),
    sa.Column('enrollment_date', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('fk_students_group_id_groups')),
    sa.PrimaryKeyConstraint('student_id', name=op.f('pk_students')),
    sa.UniqueConstraint('email', name=op.f('uq_students_email')),
    sa.UniqueConstraint('login', name=op.f('uq_students_login'))
    )
    op.create_index('idx_students_archived', 'students', ['archived_at'], unique=False)
    op.create_table('teacher_audit_log',
    sa.Column('audit_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.BigInteger(), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_id', sa.BigInteger(), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('ip_addr', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_teacher_audit_log_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('audit_id', name=op.f('pk_teacher_audit_log'))
    )
    op.create_index('idx_teacher_audit_action', 'teacher_audit_log', ['action', sa.literal_column('created_at DESC')], unique=False)
    op.create_index('idx_teacher_audit_teacher', 'teacher_audit_log', ['teacher_id', sa.literal_column('created_at DESC')], unique=False)
    op.create_table('teacher_groups',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], name=op.f('fk_teacher_groups_group_id_groups'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_teacher_groups_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'group_id', name=op.f('pk_teacher_groups'))
    )
    op.create_index('idx_teacher_groups_group', 'teacher_groups', ['group_id'], unique=False)
    op.create_index('idx_teacher_groups_teacher', 'teacher_groups', ['teacher_id'], unique=False)
    op.create_table('attempts_policy',
    sa.Column('policy_id', sa.BigInteger(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts_allowed', sa.Integer(), server_default='1', nullable=False),
    sa.Column('shuffle_seed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_correct_after_finish', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('proctor_min_level', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], name=op.f('fk_attempts_policy_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_attempts_policy_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('policy_id', name=op.f('pk_attempts_policy')),
    sa.UniqueConstraint('teacher_id', 'discipline_id', name='uq_policy_teacher_disc')
    )
    op.create_table('discipline_images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], name=op.f('fk_discipline_images_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_discipline_images')),
    sa.UniqueConstraint('discipline_id', name=op.f('uq_discipline_images_discipline_id')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_discipline_images_storage_key'))
    )
    op.create_table('discipline_topics',
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sort_order', sa.Integer(), server_default='100', nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['teachers.teacher_id'], name=op.f('fk_discipline_topics_created_by_teachers')),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], name=op.f('fk_discipline_topics_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('topic_id', name=op.f('pk_discipline_topics')),
    sa.UniqueConstraint('discipline_id', 'name', name='uq_discipline_topics_discipline_name')
    )
    op.create_index('idx_discipline_topics_discipline', 'discipline_topics', ['discipline_id'], unique=False)
    op.create_table('teacher_disciplines',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), server_default='30', nullable=False),
    sa.Column('question_count', sa.Integer(), server_default='10', nullable=False),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], name=op.f('fk_teacher_disciplines_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_teacher_disciplines_teacher_id_teachers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'discipline_id', name=op.f('pk_teacher_disciplines'))
    )
    op.create_table('discipline_topic_images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['topic_id'], ['discipline_topics.topic_id'], name=op.f('fk_discipline_topic_images_topic_id_discipline_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_discipline_topic_images')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_discipline_topic_images_storage_key')),
    sa.UniqueConstraint('topic_id', name=op.f('uq_discipline_topic_images_topic_id'))
    )
    op.create_table('questions',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Integer(), server_default='1', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('qtype', sa.String(length=16), server_default='single', nullable=False),
    sa.Column('short_pattern', sa.String(length=255), nullable=True),
    sa.Column('numeric_tolerance', sa.Numeric(), nullable=True),
    sa.Column('match_pairs', sa.JSON(), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('correct_bool', sa.Boolean(), nullable=True),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trim_whitespace', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('normalize_universal', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('text_mode', sa.String(length=8), server_default='string', nullable=False),
    sa.Column('allow_partial', sa.Boolean(), server_default='false', nullable=False),
    sa.CheckConstraint("qtype IN ('single','multi','short','numeric','match','text','order','bool','cloze')", name=op.f('ck_questions_questions_qtype_check')),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], name=op.f('fk_questions_discipline_id_disciplines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['discipline_topics.topic_id'], name=op.f('fk_questions_topic_id_discipline_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('question_id', name=op.f('pk_questions'))
    )
    op.create_index('idx_questions_archived', 'questions', ['archived_at'], unique=False)
    op.create_index('idx_questions_discipline_archived', 'questions', ['discipline_id', 'archived_at'], unique=False)
    op.create_index('idx_questions_topic', 'questions', ['topic_id'], unique=False)
    op.create_table('teacher_topic_tests',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=False),
    sa.Column('time_limit_minutes', sa.Integer(), server_default='20', nullable=False),
    sa.Column('question_count', sa.Integer(), server_default='10', nullable=False),
    sa.Column('attempts_allowed', sa.Integer(), server_default='1', nullable=False),
    sa.Column('available_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('available_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shuffle_seed', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('show_correct_after_finish', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_teacher_topic_tests_teacher_id_teachers'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['topic_id'], ['discipline_topics.topic_id'], name=op.f('fk_teacher_topic_tests_topic_id_discipline_topics'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('teacher_id', 'topic_id', name=op.f('pk_teacher_topic_tests'))
    )
    op.create_index('idx_teacher_topic_tests_topic', 'teacher_topic_tests', ['topic_id'], unique=False)
    op.create_table('test_sessions',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('discipline_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.BigInteger(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), server_default='1', nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('force_finished_by', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default='in_progress', nullable=False),
    sa.CheckConstraint("status IN ('in_progress','completed','abandoned','force_finished')", name=op.f('ck_test_sessions_test_sessions_status_check')),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.discipline_id'], name=op.f('fk_test_sessions_discipline_id_disciplines')),
    sa.ForeignKeyConstraint(['student_id'], ['students.student_id'], name=op.f('fk_test_sessions_student_id_students')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_test_sessions_teacher_id_teachers')),
    sa.ForeignKeyConstraint(['topic_id'], ['discipline_topics.topic_id'], name=op.f('fk_test_sessions_topic_id_discipline_topics'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_test_sessions'))
    )
    op.create_index('idx_sessions_active', 'test_sessions', ['discipline_id', 'student_id'], unique=False, postgresql_where=sa.text('completed_at IS NULL'))
    op.create_index('idx_sessions_attempt', 'test_sessions', ['student_id', 'discipline_id', 'attempt_no'], unique=False)
    op.create_index('idx_test_sessions_topic', 'test_sessions', ['topic_id'], unique=False)
    op.create_table('answer_comments',
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_answer_comments_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.session_id'], name=op.f('fk_answer_comments_session_id_test_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_answer_comments_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('comment_id', name=op.f('pk_answer_comments'))
    )
    op.create_table('answer_options',
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('option_number', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('match_left', sa.String(length=255), nullable=True),
    sa.Column('match_right', sa.String(length=255), nullable=True),
    sa.Column('correct_position', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_answer_options_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('option_id', name=op.f('pk_answer_options'))
    )
    op.create_index('idx_answer_options_correct_position', 'answer_options', ['question_id', 'correct_position'], unique=False)
    op.execute(sa.text("""
CREATE OR REPLACE FUNCTION fn_check_qtype_options() RETURNS trigger AS $$
DECLARE
    qt VARCHAR(16);
    cnt INTEGER;
    target_id BIGINT;
BEGIN
    target_id := COALESCE(NEW.question_id, OLD.question_id);
    SELECT qtype INTO qt FROM questions WHERE question_id = target_id;
    IF qt IS NULL THEN
        RETURN COALESCE(NEW, OLD);
    END IF;

    IF qt IN ('single','short','numeric') THEN
        IF TG_OP IN ('INSERT','UPDATE') AND NEW.is_correct THEN
            SELECT COUNT(*) INTO cnt
              FROM answer_options
             WHERE question_id = target_id AND is_correct = TRUE
               AND option_id <> COALESCE(NEW.option_id, -1);
            IF cnt >= 1 THEN
                RAISE EXCEPTION 'question of type % allows only one correct option (have %)', qt, cnt;
            END IF;
        END IF;
        IF TG_OP = 'INSERT' THEN
            SELECT COUNT(*) INTO cnt FROM answer_options WHERE question_id = target_id;
            IF cnt >= 4 THEN
                RAISE EXCEPTION 'question % already has 4 options', target_id;
            END IF;
        END IF;
    ELSIF qt = 'multi' THEN
        IF TG_OP IN ('INSERT','UPDATE') AND NEW.is_correct THEN
            SELECT COUNT(*) INTO cnt
              FROM answer_options
             WHERE question_id = target_id AND is_correct = TRUE
               AND option_id <> COALESCE(NEW.option_id, -1);
            IF cnt >= 3 THEN
                RAISE EXCEPTION 'multi question allows max 3 correct options';
            END IF;
        END IF;
    ELSIF qt = 'match' THEN
        IF NEW.match_left IS NULL OR NEW.match_right IS NULL THEN
            RAISE EXCEPTION 'match-option must have both match_left and match_right';
        END IF;
    END IF;

    RETURN COALESCE(NEW, OLD);
END $$ LANGUAGE plpgsql;
"""))
    op.execute(sa.text("DROP TRIGGER IF EXISTS trg_check_qtype_options ON answer_options;"))
    op.execute(sa.text("""
CREATE TRIGGER trg_check_qtype_options
BEFORE INSERT OR UPDATE OR DELETE ON answer_options
FOR EACH ROW EXECUTE FUNCTION fn_check_qtype_options();
"""))
    op.create_table('proctor_events',
    sa.Column('event_id', sa.BigInteger(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.session_id'], name=op.f('fk_proctor_events_session_id_test_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('event_id', name=op.f('pk_proctor_events'))
    )
    op.create_index('idx_proctor_session', 'proctor_events', ['session_id'], unique=False)
    op.create_table('question_acceptable_answers',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('ord', sa.Integer(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_question_acceptable_answers_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'ord', name=op.f('pk_question_acceptable_answers'))
    )
    op.create_index('idx_question_acceptable_answers_qid', 'question_acceptable_answers', ['question_id'], unique=False)
    op.create_table('question_cloze_blanks',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('blank_index', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_index', sa.Integer(), nullable=True),
    sa.Column('acceptable_answers', sa.JSON(), nullable=True),
    sa.Column('case_sensitive', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('trim_whitespace', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('normalize_universal', sa.Boolean(), server_default='true', nullable=False),
    sa.CheckConstraint('blank_index BETWEEN 1 AND 3', name=op.f('ck_question_cloze_blanks_chk_blank_index')),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_question_cloze_blanks_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'blank_index', name=op.f('pk_question_cloze_blanks'))
    )
    op.create_table('question_images',
    sa.Column('image_id', sa.BigInteger(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=True),
    sa.Column('height_px', sa.Integer(), nullable=True),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_question_images_question_id_questions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('image_id', name=op.f('pk_question_images')),
    sa.UniqueConstraint('question_id', name=op.f('uq_question_images_question_id')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_question_images_storage_key'))
    )
    op.create_index('idx_question_images_question_id', 'question_images', ['question_id'], unique=False)
    op.create_table('question_tag_map',
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_question_tag_map_question_id_questions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['question_tags.tag_id'], name=op.f('fk_question_tag_map_tag_id_question_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id', 'tag_id', name=op.f('pk_question_tag_map'))
    )
    op.create_table('test_sessions_grade_override',
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.session_id'], name=op.f('fk_test_sessions_grade_override_session_id_test_sessions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('fk_test_sessions_grade_override_teacher_id_teachers')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_test_sessions_grade_override'))
    )
    op.create_table('student_answers',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('selected_option_id', sa.Integer(), nullable=True),
    sa.Column('answered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.question_id'], name=op.f('fk_student_answers_question_id_questions')),
    sa.ForeignKeyConstraint(['selected_option_id'], ['answer_options.option_id'], name=op.f('fk_student_answers_selected_option_id_answer_options')),
    sa.ForeignKeyConstraint(['session_id'], ['test_sessions.session_id'], name=op.f('fk_student_answers_session_id_test_sessions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id', name=op.f('pk_student_answers')),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_one_answer_per_question_in_session')
    )
    op.create_table('answer_extra',
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('short_answer_raw', sa.Text(), nullable=True),
    sa.Column('short_answer_ok', sa.Boolean(), nullable=True),
    sa.Column('match_pairs', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['answer_id'], ['student_answers.answer_id'], name=op.f('fk_answer_extra_answer_id_student_answers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('answer_id', name=op.f('pk_answer_extra'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(sa.text("DROP TRIGGER IF EXISTS trg_check_qtype_options ON answer_options;"))
    op.execute(sa.text("DROP FUNCTION IF EXISTS fn_check_qtype_options();"))
    op.drop_table('answer_extra')
    op.drop_table('student_answers')
    op.drop_table('test_sessions_grade_override')
    op.drop_table('question_tag_map')
    op.drop_index('idx_question_images_question_id', table_name='question_images')
    op.drop_table('question_images')
    op.drop_table('question_cloze_blanks')
    op.drop_index('idx_question_acceptable_answers_qid', table_name='question_acceptable_answers')
    op.drop_table('question_acceptable_answers')
    op.drop_index('idx_proctor_session', table_name='proctor_events')
    op.drop_table('proctor_events')
    op.drop_index('idx_answer_options_correct_position', table_name='answer_options')
    op.drop_table('answer_options')
    op.drop_table('answer_comments')
    op.drop_index('idx_test_sessions_topic', table_name='test_sessions')
    op.drop_index('idx_sessions_attempt', table_name='test_sessions')
    op.drop_index('idx_sessions_active', table_name='test_sessions', postgresql_where=sa.text('completed_at IS NULL'))
    op.drop_table('test_sessions')
    op.drop_index('idx_teacher_topic_tests_topic', table_name='teacher_topic_tests')
    op.drop_table('teacher_topic_tests')
    op.drop_index('idx_questions_topic', table_name='questions')
    op.drop_index('idx_questions_discipline_archived', table_name='questions')
    op.drop_index('idx_questions_archived', table_name='questions')
    op.drop_table('questions')
    op.drop_table('discipline_topic_images')
    op.drop_table('teacher_disciplines')
    op.drop_index('idx_discipline_topics_discipline', table_name='discipline_topics')
    op.drop_table('discipline_topics')
    op.drop_table('discipline_images')
    op.drop_table('attempts_policy')
    op.drop_index('idx_teacher_groups_teacher', table_name='teacher_groups')
    op.drop_index('idx_teacher_groups_group', table_name='teacher_groups')
    op.drop_table('teacher_groups')
    op.drop_index('idx_teacher_audit_teacher', table_name='teacher_audit_log')
    op.drop_index('idx_teacher_audit_action', table_name='teacher_audit_log')
    op.drop_table('teacher_audit_log')
    op.drop_index('idx_students_archived', table_name='students')
    op.drop_table('students')
    op.drop_index('idx_disciplines_archived', table_name='disciplines')
    op.drop_table('disciplines')
    op.drop_table('user_credentials')
    op.drop_index('idx_teachers_archived', table_name='teachers')
    op.drop_table('teachers')
    op.drop_index('uq_question_tags_name_active', table_name='question_tags', postgresql_where=sa.text('archived_at IS NULL'))
    op.drop_index('idx_question_tags_archived', table_name='question_tags')
    op.drop_table('question_tags')
    op.drop_table('password_reset_tokens')
    op.drop_index('idx_notifications_user', table_name='notifications')
    op.drop_index('idx_notifications_role_channel', table_name='notifications')
    op.drop_index('idx_notifications_event_type', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('idx_groups_archived', table_name='groups')
    op.drop_table('groups')
    op.drop_index('idx_audit_target', table_name='audit_log')
    op.drop_index('idx_audit_role_time', table_name='audit_log')
    op.drop_index('idx_audit_created_at', table_name='audit_log')
    op.drop_index('idx_audit_actor', table_name='audit_log')
    op.drop_index('idx_audit_action', table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index('idx_admins_archived', table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
