"""add_profile_sessions_branding

Revision ID: 9757a7246c52
Revises: 9beb514ac146
Create Date: 2026-06-28 15:49:00.563131
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers
revision: str = '9757a7246c52'
down_revision: Union[str, None] = '9beb514ac146'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_sessions',
    sa.Column('auth_session_id', sa.UUID(), nullable=False),
    sa.Column('user_role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('token_jti', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_reason', sa.String(length=64), nullable=True),
    sa.Column('ip_addr', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_name', sa.String(length=160), nullable=True),
    sa.Column('client_kind', sa.String(length=16), nullable=False),
    sa.Column('os_name', sa.String(length=80), nullable=True),
    sa.Column('os_version', sa.String(length=80), nullable=True),
    sa.Column('browser_name', sa.String(length=80), nullable=True),
    sa.Column('browser_version', sa.String(length=80), nullable=True),
    sa.Column('app_version', sa.String(length=80), nullable=True),
    sa.Column('locale', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=64), nullable=True),
    sa.Column('geo_country', sa.String(length=80), nullable=True),
    sa.Column('geo_region', sa.String(length=120), nullable=True),
    sa.Column('geo_city', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.CheckConstraint("client_kind IN ('web', 'tauri')", name=op.f('ck_auth_sessions_chk_auth_session_client_kind')),
    sa.CheckConstraint("user_role IN ('student', 'teacher', 'admin')", name=op.f('ck_auth_sessions_chk_auth_session_role')),
    sa.PrimaryKeyConstraint('auth_session_id', name=op.f('pk_auth_sessions')),
    sa.UniqueConstraint('token_jti', name=op.f('uq_auth_sessions_token_jti'))
    )
    op.create_index('idx_auth_sessions_expires', 'auth_sessions', ['expires_at'], unique=False)
    op.create_index('idx_auth_sessions_user_active', 'auth_sessions', ['user_role', 'user_id', 'revoked_at', 'last_seen_at'], unique=False)
    op.create_table('branding_assets',
    sa.Column('asset_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('asset_kind', sa.String(length=32), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('display_width_px', sa.Integer(), nullable=True),
    sa.Column('display_height_px', sa.Integer(), nullable=True),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('created_by_admin_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("asset_kind IN ('topbar_logo', 'institution_logo', 'login_banner')", name=op.f('ck_branding_assets_chk_branding_asset_kind')),
    sa.PrimaryKeyConstraint('asset_id', name=op.f('pk_branding_assets')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_branding_assets_storage_key'))
    )
    op.create_index('idx_branding_assets_kind_created', 'branding_assets', ['asset_kind', 'created_at'], unique=False)
    op.create_table('user_avatar_images',
    sa.Column('avatar_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_role', sa.String(length=16), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('storage_key', sa.Text(), nullable=False),
    sa.Column('original_name', sa.Text(), nullable=True),
    sa.Column('content_type', sa.String(length=64), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('width_px', sa.Integer(), nullable=False),
    sa.Column('height_px', sa.Integer(), nullable=False),
    sa.Column('sha256_hex', sa.String(length=64), nullable=False),
    sa.Column('crop_json', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("user_role IN ('student', 'teacher', 'admin')", name=op.f('ck_user_avatar_images_chk_user_avatar_role')),
    sa.PrimaryKeyConstraint('avatar_id', name=op.f('pk_user_avatar_images')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_user_avatar_images_storage_key'))
    )
    op.create_index('idx_user_avatar_images_user', 'user_avatar_images', ['user_role', 'user_id', 'created_at'], unique=False)
    op.create_table('app_branding_settings',
    sa.Column('settings_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('app_name', sa.String(length=80), nullable=False),
    sa.Column('topbar_logo_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('institution_logo_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('institution_logo_display_size_px', sa.Integer(), server_default='56', nullable=False),
    sa.Column('login_banner_asset_id', sa.BigInteger(), nullable=True),
    sa.Column('login_banner_enabled', sa.Boolean(), nullable=False),
    sa.Column('updated_by_role', sa.String(length=16), nullable=True),
    sa.Column('updated_by_id', sa.BigInteger(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('institution_logo_display_size_px BETWEEN 40 AND 96', name=op.f('ck_app_branding_settings_chk_institution_logo_display_size')),
    sa.CheckConstraint('settings_id = 1', name=op.f('ck_app_branding_settings_singleton_branding_settings')),
    sa.ForeignKeyConstraint(['institution_logo_asset_id'], ['branding_assets.asset_id'], name=op.f('fk_app_branding_settings_institution_logo_asset_id_branding_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['login_banner_asset_id'], ['branding_assets.asset_id'], name=op.f('fk_app_branding_settings_login_banner_asset_id_branding_assets'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['topbar_logo_asset_id'], ['branding_assets.asset_id'], name=op.f('fk_app_branding_settings_topbar_logo_asset_id_branding_assets'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('settings_id', name=op.f('pk_app_branding_settings'))
    )
    op.execute(
        """
        INSERT INTO app_branding_settings (settings_id, app_name, institution_logo_display_size_px, login_banner_enabled)
        VALUES (1, 'Верифика', 56, FALSE)
        ON CONFLICT (settings_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_branding_settings')
    op.drop_index('idx_user_avatar_images_user', table_name='user_avatar_images')
    op.drop_table('user_avatar_images')
    op.drop_index('idx_branding_assets_kind_created', table_name='branding_assets')
    op.drop_table('branding_assets')
    op.drop_index('idx_auth_sessions_user_active', table_name='auth_sessions')
    op.drop_index('idx_auth_sessions_expires', table_name='auth_sessions')
    op.drop_table('auth_sessions')
    # ### end Alembic commands ###
