"""add_allow_study_to_teacher_topic_tests

Revision ID: 9beb514ac146
Revises: b64ef90b6178
Create Date: 2026-06-28 15:17:06.500443
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers
revision: str = '9beb514ac146'
down_revision: Union[str, None] = 'b64ef90b6178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teacher_topic_tests', sa.Column('allow_study', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teacher_topic_tests', 'allow_study')
    # ### end Alembic commands ###
